let EventTypes = {};
[
  'CONFIGURE_CHANGE_ERROR',
  'CONFIGURE_CHANGE_SUCCESS',
  'CONFIGURE_FORM_COMPLETION_CHANGE',
  'CONFIGURE_STATUS_CHANGE_ERROR',
  'CONFIGURE_STATUS_CHANGE_SUCCESS',
  'CONFIGURE_TYPE_CHANGE_ERROR',
  'CONFIGURE_TYPE_CHANGE_SUCCESS',
  'CONFIGURE_UPDATE_FIELD_ERROR',
  'CONFIGURE_UPDATE_FIELD_SUCCESS',
  'CURRENT_STAGE_CHANGE',
  'DCOS_URL_CHANGE',
  'DEPLOY_BEGIN_SUCCESS',
  'DEPLOY_BEGIN_ERROR',
  'DEPLOY_STATE_CHANGE',
  'DEPLOY_STATE_FINISH',
  'GLOBAL_INSTALL_IN_PROGRESS_CHANGE',
  'GLOBAL_NEXT_STEP_CHANGE',
  'PREFLIGHT_STATE_CHANGE',
  'PREFLIGHT_STATE_FINISH',
  'PREFLIGHT_BEGIN_SUCCESS',
  'PREFLIGHT_BEGIN_ERROR',
  'POSTFLIGHT_STATE_CHANGE',
  'POSTFLIGHT_STATE_FINISH',
  'POSTFLIGHT_BEGIN_SUCCESS',
  'POSTFLIGHT_BEGIN_ERROR',
  'TOTAL_AGENTS_ERROR',
  'TOTAL_AGENTS_SUCCESS',
  'TOTAL_MASTERS_ERROR',
  'TOTAL_MASTERS_SUCCESS',
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
