let EventTypes = {};
[
  'CURRENT_STAGE_CHANGE',
  'DEPLOY_BEGIN_SUCCESS',
  'DEPLOY_BEGIN_ERROR',
  'DEPLOY_STATE_CHANGE',
  'GLOBAL_INSTALL_IN_PROGRESS_CHANGE',
  'GLOBAL_NEXT_STEP_CHANGE',
  'PREFLIGHT_STATE_CHANGE',
  'PREFLIGHT_BEGIN_SUCCESS',
  'PREFLIGHT_BEGIN_ERROR',
  'POSTFLIGHT_STATE_CHANGE',
  'POSTFLIGHT_BEGIN_SUCCESS',
  'POSTFLIGHT_BEGIN_ERROR',
  'SETUP_USER_INPUT_VALIDATED'
].forEach(function (eventType) {
  EventTypes[eventType] = eventType;
});

module.exports = EventTypes;
